### ISSUE TITLE
Test suit failes on test.js:323 and test.js:324

### ISSUE THREAD

**Issue by gaydenko** [sylvainpolletvillard/Databinder#3]
Have got

```txt
failed
Expected: 	
"Karl"
Result: 	
""
Diff: 	
"Karl" "" 
Source: 	
@http://path/Databinder/test/test.js:323:3

failed
Expected: 	
"Karl Junior"
Result: 	
"Karl"
Diff: 	
"Karl Junior" "Karl" 
Source: 	
@http://path/Databinder/test/test.js:324:3
```
Have tried on plenty browsers (chrome, firefox. opera, midori...) with exactly the same result.

**Comment by gaydenko** [comment]
And on building with `grunt` I get the same errors.

**Comment by sylvainpolletvillard** [comment]
Thanks for the feedback. It is weird because the version on the website works (http://syllab.fr/projets/web/databinder/test/) and I do not see any differences with the version on Github. I will figure it out.

**Comment by gaydenko** [comment]
Yes, the ref on the syllab site does work for me also.

**Comment by sylvainpolletvillard** [comment]
Ok, the unit test 9 was not properly updated on Github. This should be fixed now. Thanks !

**Comment by gaydenko** [comment]
Thanks, it works now.
