### ISSUE TITLE
[Q] Arrays appending efficiency 

### ISSUE THREAD

**Issue by gaydenko** [sylvainpolletvillard/Databinder#4]
Hi!

At the moment I'm digging in the documentation and try realize what is Databinder's way to append a list of objects.  Say we want to implement a page with "infinite scrolling". For such use case it would be handy to avoid already-existing array part resetting (in terms of `reset()`), but just to append new items to the DOM. Is it possible?

**Comment by sylvainpolletvillard** [comment]
Hi there,

Yes it is, and I am working on it. The next version of Databinder will have this smart behaviour for array updates. If you add or remove some elements of a list, only the DOM nodes associated to these elements will be inserted/removed. You can have a preview of 0.9 on the dev branch: https://github.com/sylvainpolletvillard/Databinder/blob/dev/databinder.js

Databinder is still under development and there is much to come : optional two-way databinding, smart updates, extensible bindings, custom builds... My goal is to make it a valid alternative to the templating systems included in the current heavyweights frameworks, while remaining a small library easy to learn and easy to use. But this will take some time and there will be breaking changes in the API until version 1.0.

So thank you for your interest, and keep in touch. I hope to show more this summer ;)

**Comment by gaydenko** [comment]
I see, thanks!
